// input.js — Input handling: mouse, touch, keyboard
// All inputs produce InputEvent objects queued for the game loop

import { pixelToTriangle } from './grid.js';
import { touchButtons } from './hud.js';

const INPUT_QUEUE = [];
const ROTATION_DEBOUNCE_MS = 125; // max 8 per second
let lastRotationTime = 0;
let lastTouchTime = 0; // track touch events to suppress ghost clicks

/**
 * Initialize input handlers on the canvas.
 * @param {HTMLCanvasElement} canvas
 * @param {Function} getRenderParams - Returns { size, offsetX, offsetY }
 */
export function initInput(canvas, getRenderParams) {
  // ===== MOUSE =====
  canvas.addEventListener('click', (e) => {
    // Skip ghost clicks generated by touch events
    if (performance.now() - lastTouchTime < 500) return;
    const { size, offsetX, offsetY } = getRenderParams();
    const rect = canvas.getBoundingClientRect();
    const px = e.clientX - rect.left - offsetX;
    const py = e.clientY - rect.top - offsetY;
    const tri = pixelToTriangle(px, py, size);
    if (tri) {
      // Move cursor to the hex cell containing this triangle
      pushEvent({ type: 'moveCursor', target: { q: tri.q, r: tri.r }, timestamp: e.timeStamp });
    }
  });

  canvas.addEventListener('wheel', (e) => {
    e.preventDefault();
    const now = performance.now();
    if (now - lastRotationTime < ROTATION_DEBOUNCE_MS) return;
    lastRotationTime = now;
    pushEvent({
      type: e.deltaY > 0 ? 'rotateCW' : 'rotateCCW',
      timestamp: e.timeStamp,
    });
  }, { passive: false });

  // ===== KEYBOARD =====
  const keyMap = {
    'KeyQ': 'rotateCCW', 'KeyZ': 'rotateCCW',
    'KeyE': 'rotateCW', 'KeyX': 'rotateCW',
    'Space': 'pause',
    'Escape': 'escape',
  };

  // Direction keys map to cursor movement between hex cells
  const dirKeys = {
    'KeyW': 'up', 'ArrowUp': 'up',
    'KeyS': 'down', 'ArrowDown': 'down',
    'KeyA': 'left', 'ArrowLeft': 'left',
    'KeyD': 'right', 'ArrowRight': 'right',
  };

  document.addEventListener('keydown', (e) => {
    const action = keyMap[e.code];
    if (action) {
      e.preventDefault();
      if (action === 'rotateCW' || action === 'rotateCCW') {
        const now = performance.now();
        if (now - lastRotationTime < ROTATION_DEBOUNCE_MS) return;
        lastRotationTime = now;
      }
      pushEvent({ type: action, timestamp: e.timeStamp });
      return;
    }

    const dir = dirKeys[e.code];
    if (dir) {
      e.preventDefault();
      pushEvent({ type: 'moveCursorDir', direction: dir, timestamp: e.timeStamp });
    }
  });

  // ===== TOUCH =====
  let touchStartPos = null;
  let touchStartAngle = null;
  let isTwoFinger = false;

  canvas.addEventListener('touchstart', (e) => {
    e.preventDefault();
    if (e.touches.length === 1) {
      touchStartPos = { x: e.touches[0].clientX, y: e.touches[0].clientY };
      isTwoFinger = false;
    } else if (e.touches.length === 2) {
      isTwoFinger = true;
      const dx = e.touches[1].clientX - e.touches[0].clientX;
      const dy = e.touches[1].clientY - e.touches[0].clientY;
      touchStartAngle = Math.atan2(dy, dx);
    }
  }, { passive: false });

  canvas.addEventListener('touchmove', (e) => {
    e.preventDefault();
    if (e.touches.length === 2 && isTwoFinger) {
      const dx = e.touches[1].clientX - e.touches[0].clientX;
      const dy = e.touches[1].clientY - e.touches[0].clientY;
      const angle = Math.atan2(dy, dx);

      // Rotation detection: snap to 60° increments
      if (touchStartAngle !== null) {
        const delta = angle - touchStartAngle;
        if (Math.abs(delta) > Math.PI / 6) { // 30° threshold
          const now = performance.now();
          if (now - lastRotationTime >= ROTATION_DEBOUNCE_MS) {
            lastRotationTime = now;
            pushEvent({
              type: delta > 0 ? 'rotateCCW' : 'rotateCW',
              timestamp: e.timeStamp,
            });
            touchStartAngle = angle;
          }
        }
      }
    }
  }, { passive: false });

  canvas.addEventListener('touchend', (e) => {
    e.preventDefault();
    lastTouchTime = performance.now();
    if (!isTwoFinger && touchStartPos && e.changedTouches.length === 1) {
      const t = e.changedTouches[0];
      const dx = t.clientX - touchStartPos.x;
      const dy = t.clientY - touchStartPos.y;
      // Only treat as tap if finger didn't move much
      if (Math.sqrt(dx * dx + dy * dy) < 20) {
        const rect = canvas.getBoundingClientRect();
        const tapX = t.clientX - rect.left;
        const tapY = t.clientY - rect.top;

        // Check on-screen rotation buttons first
        if (touchButtons.visible) {
          const ccw = touchButtons.rotateCCW;
          const cw = touchButtons.rotateCW;
          const dCCW = Math.sqrt((tapX - ccw.x) ** 2 + (tapY - ccw.y) ** 2);
          const dCW = Math.sqrt((tapX - cw.x) ** 2 + (tapY - cw.y) ** 2);
          if (dCCW <= ccw.radius * 1.5) {
            const now = performance.now();
            if (now - lastRotationTime >= ROTATION_DEBOUNCE_MS) {
              lastRotationTime = now;
              pushEvent({ type: 'rotateCCW', timestamp: e.timeStamp });
            }
          } else if (dCW <= cw.radius * 1.5) {
            const now = performance.now();
            if (now - lastRotationTime >= ROTATION_DEBOUNCE_MS) {
              lastRotationTime = now;
              pushEvent({ type: 'rotateCW', timestamp: e.timeStamp });
            }
          } else {
            // Not a button tap — move cursor
            const { size, offsetX, offsetY } = getRenderParams();
            const px = tapX - offsetX;
            const py = tapY - offsetY;
            const tri = pixelToTriangle(px, py, size);
            if (tri) {
              pushEvent({ type: 'moveCursor', target: { q: tri.q, r: tri.r }, timestamp: e.timeStamp });
            }
          }
        } else {
          // Buttons not visible — just move cursor
          const { size, offsetX, offsetY } = getRenderParams();
          const px = tapX - offsetX;
          const py = tapY - offsetY;
          const tri = pixelToTriangle(px, py, size);
          if (tri) {
            pushEvent({ type: 'moveCursor', target: { q: tri.q, r: tri.r }, timestamp: e.timeStamp });
          }
        }
      }
    }
    if (e.touches.length === 0) {
      touchStartPos = null;
      touchStartAngle = null;
      isTwoFinger = false;
    }
  }, { passive: false });
}

/**
 * Push an event into the queue.
 */
function pushEvent(event) {
  INPUT_QUEUE.push(event);
}

/**
 * Drain all queued input events.
 */
export function drainInputQueue() {
  const events = INPUT_QUEUE.splice(0);
  return events;
}
