// main.js — Game loop orchestrator
// Ties together all modules: state, rendering, input, audio

import { createInitialState, processInput, tick, unpause, moveCursorDirection, BOARD_RADIUS } from './gamestate.js';
import { initRenderer, renderFrame, resize, getRenderParams } from './renderer.js';
import { AnimationManager } from './animations.js';
import { drawHUD, drawGameOver, drawPause, touchButtons } from './hud.js';
import { initInput, drainInputQueue } from './input.js';
import { initAudio, resumeAudio, playSound, startDrone, stopDrone } from './audio.js';
import { drawMenu, handleMenuClick, handleMenuHover, resetMenu } from './menu.js';
import { saveHighScore } from './scoring.js';
import { COLOR_PALETTE } from './progression.js';
import { hexToPixel } from './grid.js';

// App state
let appState = 'menu'; // 'menu' | 'playing' | 'gameover'
let gameState = null;
let prevGameState = null;
let animations = null;
let lastTime = 0;
let isNewHighScore = false;

// Canvas setup
const canvas = document.getElementById('gameCanvas');
const { ctx } = initRenderer(canvas);

// Responsive resize
window.addEventListener('resize', resize);

// Initialize input
initInput(canvas, getRenderParams);

// Shared handler for click/tap on menu and gameover
function handleCanvasTap(clientX, clientY) {
  initAudio();
  resumeAudio();

  if (appState === 'menu') {
    const rect = canvas.getBoundingClientRect();
    const mode = handleMenuClick(clientX - rect.left, clientY - rect.top);
    if (mode) {
      startGame(mode);
    }
  } else if (appState === 'gameover') {
    appState = 'menu';
    resetMenu();
    stopDrone();
    touchButtons.visible = false;
    drainInputQueue(); // discard stale events
  }
}

// Track touch to suppress ghost clicks
let lastMenuTouchTime = 0;

// Menu interaction handlers — click for desktop
canvas.addEventListener('click', (e) => {
  // Skip ghost clicks generated by touch events
  if (performance.now() - lastMenuTouchTime < 500) return;
  handleCanvasTap(e.clientX, e.clientY);
});

// Touch handler for menu/gameover — since touchstart preventDefault blocks click
canvas.addEventListener('touchend', (e) => {
  if (appState === 'menu' || appState === 'gameover') {
    lastMenuTouchTime = performance.now();
    if (e.changedTouches.length === 1) {
      const t = e.changedTouches[0];
      handleCanvasTap(t.clientX, t.clientY);
    }
  }
});

canvas.addEventListener('mousemove', (e) => {
  if (appState === 'menu') {
    const rect = canvas.getBoundingClientRect();
    handleMenuHover(e.clientX - rect.left, e.clientY - rect.top);
  }
});

/**
 * Start a new game.
 */
function startGame(mode) {
  appState = 'playing';
  gameState = createInitialState(mode);
  prevGameState = null;
  animations = new AnimationManager();
  isNewHighScore = false;
  startDrone(gameState.activeColors.length);
}

/**
 * Main game loop.
 */
function gameLoop(timestamp) {
  const dt = lastTime ? Math.min(timestamp - lastTime, 50) : 16;
  lastTime = timestamp;

  const w = canvas.width / (window.devicePixelRatio || 1);
  const h = canvas.height / (window.devicePixelRatio || 1);

  if (appState === 'menu') {
    drawMenu(ctx, w, h);
  } else if (appState === 'playing' || appState === 'gameover') {
    // Process inputs
    const events = drainInputQueue();
    for (const event of events) {
      if (event.type === 'escape') {
        appState = 'menu';
        resetMenu();
        stopDrone();
        touchButtons.visible = false;
        drainInputQueue(); // discard stale events
        requestAnimationFrame(gameLoop);
        return;
      }

      if (event.type === 'pause') {
        if (gameState.phase === 'paused') {
          gameState = unpause(gameState);
        } else if (gameState.phase === 'playing') {
          gameState = processInput(gameState, event);
        }
        continue;
      }

      if (event.type === 'moveCursorDir') {
        gameState = moveCursorDirection(gameState, event.direction);
        continue;
      }

      if (gameState.phase === 'playing') {
        prevGameState = gameState;
        gameState = processInput(gameState, event);

        // Audio triggers based on input
        if (event.type === 'rotateCW' || event.type === 'rotateCCW') {
          playSound('rotate');
        }
      }
    }

    // Tick game state
    if (gameState.phase !== 'paused') {
      prevGameState = gameState;
      gameState = tick(gameState, dt);
    }

    // Detect state changes for audio
    if (prevGameState && gameState !== prevGameState) {
      // Hex cleared
      if (gameState.justCleared.length > 0) {
        for (const hex of gameState.justCleared) {
          playSound('clear', { colorIndex: hex.color });
          // Spawn particles
          const { size, offsetX, offsetY } = getRenderParams();
          const hCenter = hexToPixel(hex.hexCoord.q, hex.hexCoord.r, size);
          animations.spawnClearParticles(
            hCenter.x + offsetX,
            hCenter.y + offsetY,
            COLOR_PALETTE[hex.color]
          );
          animations.triggerShake();
        }
      }

      // Level up
      if (gameState.leveledUp) {
        playSound('levelup', { colorIndex: gameState.activeColors[gameState.activeColors.length - 1] });
        startDrone(gameState.activeColors.length);
      }

      // Game over
      if (gameState.phase === 'gameover' && prevGameState.phase !== 'gameover') {
        playSound('gameover');
        stopDrone();
        isNewHighScore = saveHighScore(gameState.mode, gameState.score);
        appState = 'gameover';
      }

      // Drop happened
      if (gameState.justDropped) {
        playSound('place', { colorIndex: gameState.activeColors[0] });
      }
    }

    // Update animations
    animations.update(dt);

    // Render
    renderFrame({ state: gameState, animations, dt });
    drawHUD(ctx, gameState, w, h);

    // Overlays
    if (gameState.phase === 'gameover') {
      drawGameOver(ctx, gameState, w, h, isNewHighScore);
    } else if (gameState.phase === 'paused') {
      drawPause(ctx, w, h);
    }
  }

  requestAnimationFrame(gameLoop);
}

// Start the loop
requestAnimationFrame(gameLoop);
